In [1]:
import numpy as np #importnumpy

In [2]:
myList = [1,2,3,4,5,6,7] #insert a list

In [3]:
type(myList) #check type of list

list

In [5]:
np.array(myList) #convert myList to array

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
myList

[1, 2, 3, 4, 5, 6, 7]

In [8]:
myarr = np.array(myList) #store myList array into myarr

In [9]:
myarr #print myarr

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
type(myarr) #check type of myarr

numpy.ndarray

In [17]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
type(matrix)

list

In [20]:
mymatrix = np.array(matrix) #convert list to matrix
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
type(mymatrix) #check type

numpy.ndarray

In [16]:
np.arange(0,10) #create numpy array in between given range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,10,2) #create numpy array in between given range with given steps

array([0, 2, 4, 6, 8])

In [23]:
np.zeros(10) #create given zeros array with given no of index

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((5,5)) #create 5x5 zeros matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(10) #create given ones array with given no of index

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((5,5)) #create 5x5 ones matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.linspace(0,10,3) #print 3 numbers in given range with equal distance

array([ 0.,  5., 10.])

In [36]:
 a= np.linspace(0,100,14) #print 14 numbers in given range with equal distance
a

array([  0.        ,   7.69230769,  15.38461538,  23.07692308,
        30.76923077,  38.46153846,  46.15384615,  53.84615385,
        61.53846154,  69.23076923,  76.92307692,  84.61538462,
        92.30769231, 100.        ])

In [37]:
len(a)

14

In [38]:
np.eye(5) #print identical 5x5 matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.random.rand(5) #create array with 5 random values

array([0.24930137, 0.13421801, 0.47191489, 0.38928591, 0.44252481])

In [44]:
np.random.rand(5,3) #crate 5x3 matrix with random values

array([[0.89825735, 0.58515781, 0.20248969],
       [0.55053299, 0.44173861, 0.83608515],
       [0.27866264, 0.89694611, 0.69254023],
       [0.60956602, 0.86370864, 0.88583599],
       [0.96569859, 0.8605491 , 0.43609241]])

In [59]:
np.random.randn(10)

array([ 0.30483317,  0.3821397 , -2.72529308,  0.54569372, -2.32537711,
        1.42205054, -0.67960949, -0.54425613, -1.45743774, -0.12156284])

In [60]:
np.random.randn(2,3)

array([[ 0.7208683 ,  0.97430314, -0.15475942],
       [ 2.66971922,  0.52517238, -2.26791778]])

In [61]:
np.random.randint(0,99,10) #create array with 10 random int numbers in between 0 to 99

array([ 8, 57,  9, 34, 44, 54, 23, 45, 75, 48])

In [63]:
np.random.randint(0,99,(4,5)) #create 4x5 matrix in between 0 to 99

array([[73, 35, 27, 42,  3],
       [ 7, 64, 94, 50, 59],
       [68, 50, 50, 30, 77],
       [45, 98, 45, 98, 74]])

In [ ]:
'''
When seed value is same then random value also be same.
it is not affect that use in diff cells
'''

In [64]:
np.random.seed(45)
np.random.rand(5)

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ])

In [69]:
np.random.seed(45)
np.random.rand(5)

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ])

In [70]:
np.random.rand(5)

array([0.47280797, 0.048522  , 0.16332445, 0.11595071, 0.62739168])

In [71]:
np.random.rand(5)

array([0.85618205, 0.65010242, 0.99072168, 0.47035075, 0.61829448])

In [67]:
np.random.seed(40)
np.random.rand(5)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518, 0.45035059])

In [72]:
np.random.seed(40)
np.random.rand(5)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518, 0.45035059])

In [75]:
arr = np.arange(0,20) #create array for given range
arr.reshape(4,5) #reshape above array to 4x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
ranarr = np.random.randint(0,101,10)
ranarr

array([19, 31, 74, 55, 83, 59, 91, 73, 96, 49])

In [77]:
ranarr.max() #print max value in given array

96

In [78]:
ranarr.min() #print min value in given array

19

In [79]:
ranarr.argmax() #print index of max value in given array

8

In [80]:
ranarr.argmin() #print index of min value

0

In [81]:
ranarr.dtype

dtype('int32')

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
m1 = arr.reshape(4,5)
m1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
m1.min()

0

In [87]:
m1.argmin()

0

In [88]:
m1.max()

19

In [89]:
m1.argmax()

19

In [90]:
'''
for more about numpy visit 
https://numpy.org/doc/
'''

'\nfor more about numpy visit \nhttps://numpy.org/doc/\n'