In [2]:
import numpy as np #importnumpy

In [3]:
myList = [1,2,3,4,5,6,7] #insert a list

In [4]:
type(myList) #check type of list

list

In [5]:
np.array(myList) #convert myList to array

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
myList

[1, 2, 3, 4, 5, 6, 7]

In [7]:
myarr = np.array(myList) #store myList array into myarr

In [8]:
myarr #print myarr

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
type(myarr) #check type of myarr

numpy.ndarray

In [10]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
type(matrix)

list

In [12]:
mymatrix = np.array(matrix) #convert list to matrix
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
type(mymatrix) #check type

numpy.ndarray

In [14]:
np.arange(0,10) #create numpy array in between given range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2) #create numpy array in between given range with given steps

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(10) #create given zeros array with given no of index

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,5)) #create 5x5 zeros matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(10) #create given ones array with given no of index

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((5,5)) #create 5x5 ones matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,10,3) #print 3 numbers in given range with equal distance

array([ 0.,  5., 10.])

In [21]:
 a= np.linspace(0,100,14) #print 14 numbers in given range with equal distance
a

array([  0.        ,   7.69230769,  15.38461538,  23.07692308,
        30.76923077,  38.46153846,  46.15384615,  53.84615385,
        61.53846154,  69.23076923,  76.92307692,  84.61538462,
        92.30769231, 100.        ])

In [22]:
len(a)

14

In [23]:
np.eye(5) #print identical 5x5 matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(5) #create array with 5 random values

array([0.87524019, 0.60795961, 0.87160339, 0.31933706, 0.38244994])

In [25]:
np.random.rand(5,3) #crate 5x3 matrix with random values

array([[0.33265433, 0.62783434, 0.19831931],
       [0.8572821 , 0.16555309, 0.92448703],
       [0.74385433, 0.60982161, 0.40688799],
       [0.37482224, 0.61795331, 0.94991012],
       [0.9373017 , 0.65451342, 0.11622185]])

In [26]:
np.random.randn(10)

array([-0.29661375, -0.60347682, -0.71015708, -0.07508767, -0.09134289,
        1.20333977, -1.2325636 , -0.72246086,  1.78503534,  0.01493945])

In [27]:
np.random.randn(2,3)

array([[-0.77643761, -1.38604041,  1.89018468],
       [ 0.29945219, -0.26315703,  0.21896825]])

In [28]:
np.random.randint(0,99,10) #create array with 10 random int numbers in between 0 to 99

array([95, 95, 27,  2, 23, 48, 94, 45, 22, 46])

In [29]:
np.random.randint(0,99,(4,5)) #create 4x5 matrix in between 0 to 99

array([[29, 67,  8,  4, 48],
       [85, 49, 19, 32, 76],
       [ 1, 18, 73, 23, 96],
       [42, 42, 67, 54, 69]])

In [30]:
'''
When seed value is same then random value also be same.
it is not affect that use in diff cells
'''

'\nWhen seed value is same then random value also be same.\nit is not affect that use in diff cells\n'

In [31]:
np.random.seed(45)
np.random.rand(5)

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ])

In [32]:
np.random.seed(45)
np.random.rand(5)

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ])

In [33]:
np.random.rand(5)

array([0.47280797, 0.048522  , 0.16332445, 0.11595071, 0.62739168])

In [34]:
np.random.rand(5)

array([0.85618205, 0.65010242, 0.99072168, 0.47035075, 0.61829448])

In [35]:
np.random.seed(40)
np.random.rand(5)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518, 0.45035059])

In [36]:
np.random.seed(40)
np.random.rand(5)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518, 0.45035059])

In [37]:
arr = np.arange(0,20) #create array for given range
arr.reshape(4,5) #reshape above array to 4x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
ranarr = np.random.randint(0,101,10)
ranarr

array([19, 31, 74, 55, 83, 59, 91, 73, 96, 49])

In [39]:
ranarr.max() #print max value in given array

96

In [40]:
ranarr.min() #print min value in given array

19

In [41]:
ranarr.argmax() #print index of max value in given array

8

In [42]:
ranarr.argmin() #print index of min value

0

In [43]:
ranarr.dtype

dtype('int32')

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
m1 = arr.reshape(4,5)
m1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
m1.min()

0

In [47]:
m1.argmin()

0

In [48]:
m1.max()

19

In [49]:
m1.argmax()

19

In [50]:
'''
for more about numpy visit 
https://numpy.org/doc/
'''

'\nfor more about numpy visit \nhttps://numpy.org/doc/\n'

In [51]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[1] 

1

In [53]:
arr[1:5]

array([1, 2, 3, 4])

In [54]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[:5]

array([0, 1, 2, 3, 4])

In [56]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[0:5] = 99 #change 0 to 5 index value to 99
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [59]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
slice_arr = arr[0:5] #copy 0 to 5 index values in slice_arr from arr
slice_arr

array([0, 1, 2, 3, 4])

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
slice_arr[:] = 101 #change all value to 101

In [63]:
slice_arr

array([101, 101, 101, 101, 101])

In [64]:
arr #check original arr values also change after making changes in slice_arr

array([101, 101, 101, 101, 101,   5,   6,   7,   8,   9,  10])

In [65]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
copy_arr = arr.copy()
copy_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
copy_arr[:] = 100
copy_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr1 = np.array([[21,9,99],[22,7,99],[20,9,99]])
arr1

array([[21,  9, 99],
       [22,  7, 99],
       [20,  9, 99]])

In [70]:
arr1.shape

(3, 3)

In [71]:
arr1[2]

array([20,  9, 99])

In [72]:
arr1[1][1]

7

In [73]:
arr1[1,1]

7

In [74]:
arr1[:2]

array([[21,  9, 99],
       [22,  7, 99]])

In [75]:
arr1[1:]

array([[22,  7, 99],
       [20,  9, 99]])

In [76]:
arr1[:2,1:]

array([[ 9, 99],
       [ 7, 99]])

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [79]:
bool_arr = arr < 5

In [80]:
bool_arr

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [81]:
arr[bool_arr]

array([0, 1, 2, 3, 4])

In [82]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr + 5 #add 5 from array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [86]:
arr - 2 #sub 2 from array

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [87]:
arr * 3 #multiply 3 from array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [88]:
arr / 3 #div 3 from array

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333])

In [89]:
arr + arr #add array into array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [90]:
arr - arr #sub array from array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
arr * arr #multiply array to array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
arr / arr #div array from array

C:\Users\ACER\AppData\Local\Temp\ipykernel_2116\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
np.sqrt(arr) #find squre root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [94]:
np.sin(arr) #find sin of given array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [95]:
np.log(arr) #find log of given array

C:\Users\ACER\AppData\Local\Temp\ipykernel_2116\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [101]:
arr.sum() #sum of array

55

In [102]:
arr.mean() #mean of array

5.0

In [103]:
arr.max() #max of array

10

In [104]:
arr.min() #min of array

0

In [105]:
arr.var() #variance of array

10.0

In [106]:
arr.std() #standard deviation

3.1622776601683795

In [107]:
arr1 = np.arange(0,25).reshape(5,5)

In [108]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [109]:
arr1.sum()

300

In [110]:
arr1.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [111]:
arr1.sum(axis = 1)

array([ 10,  35,  60,  85, 110])